; Overlay runtime (resident).
;
; An overlay function F is reached through a thunk, generated by ovlgen.py:
;
;       F:  jsr __ovl_call
;           .byte  <overlay id>
;           .short F.body
;
; __ovl_call pops the thunk's return address to find that inline data, maps the
; overlay into the window (if it is not there already), calls F.body, then maps
; the caller's overlay back and returns to the caller.
;
; It preserves A and X (arguments in, results out) and never touches the
; imaginary registers (__rc*), so the llvm-mos calling convention is intact.
; Interrupts must be off (the map is briefly inconsistent), and it is not
; re-entrant from interrupt context.
;
; Overlay 0 means "no overlay mapped". The map values per overlay are in the
; generated tables __ovl_tab_a / __ovl_tab_x.

	.zeropage	__ovl_p
	.zeropage	__ovl_tgt
	.zeropage	__ovl_id
	.zeropage	__ovl_sa
	.zeropage	__ovl_sx

	.section	.zp.bss,"aw",@nobits
	.globl	__ovl_p
__ovl_p:	.zero	2
	.globl	__ovl_tgt
__ovl_tgt:	.zero	2
	.globl	__ovl_id
__ovl_id:	.zero	1
	.globl	__ovl_sa
__ovl_sa:	.zero	1
	.globl	__ovl_sx
__ovl_sx:	.zero	1

	.section	.bss.__ovl_cur,"aw",@nobits
	.globl	__ovl_cur
__ovl_cur:	.zero	1

; Startup: clear the memory map before the C runtime initialises .data and
; .bss (.init.200), so that they are set up in the RAM we keep using. Runs
; after unmap-basic (.init.010). The KERNAL stays visible: ROM banking is done
; by $01/$D030, and only blocks MAPped over $E000 would hide it.
	.section	.init.020,"ax",@progbits
	lda	#$00
	ldx	#$00
	ldy	#$00
	ldz	#$00
	map
	eom

	.section	.text.__ovl_map,"ax",@progbits
; A = overlay id -> map it into the window. Clobbers A, X, Y.
	.globl	__ovl_map
__ovl_map:
	tay
	lda	__ovl_tab_x,y
	tax
	lda	__ovl_tab_a,y
	ldy	#0
	ldz	#0
	map
	eom
	rts

; Select attic megabyte $81 for the lower region. A megabyte select keeps the
; region's current offset and block mask, so the mapping must be clear first
; (it is, since .init.020, but be safe), or the blocks it has mapped move into
; attic RAM with it.
	.section	.text.__ovl_setmb,"ax",@progbits
	.globl	__ovl_setmb
__ovl_setmb:
	lda	#$00
	ldx	#$00
	ldy	#$00
	ldz	#$00
	map
	eom
	lda	#$81
	ldx	#$0f
	ldy	#$00
	ldz	#$00
	map
	eom
	rts

	.section	.text.__ovl_call,"ax",@progbits
	.globl	__ovl_call
__ovl_call:
	sta	__ovl_sa
	stx	__ovl_sx
	pla				; thunk return address -> inline data
	sta	__ovl_p
	pla
	sta	__ovl_p+1
	ldy	#1
	lda	(__ovl_p),y		; overlay id
	sta	__ovl_id
	iny
	lda	(__ovl_p),y		; target address
	sta	__ovl_tgt
	iny
	lda	(__ovl_p),y
	sta	__ovl_tgt+1

	lda	__ovl_cur
	cmp	__ovl_id
	beq	.Lsame

	pha				; remember the caller's overlay
	lda	__ovl_id
	sta	__ovl_cur
	jsr	__ovl_map
	ldx	__ovl_sx
	lda	__ovl_sa
	jsr	.Lgo
	sta	__ovl_sa		; results
	stx	__ovl_sx
	pla
	sta	__ovl_cur
	jsr	__ovl_map		; back to the caller's overlay
	lda	__ovl_sa
	ldx	__ovl_sx
	rts

.Lsame:
	ldx	__ovl_sx
	lda	__ovl_sa
.Lgo:
	jmp	(__ovl_tgt)
