#!/usr/bin/env python3
"""Reference data for the MEGA65 Huffman test (see hufftest.c).

Builds and runs a host program that expands every graphics chunk with the
*original* CAL_HuffExpand (taken from git revision BASE of id_ca.cpp), and
writes a C header with each chunk's expanded length and checksum.

usage: gen_huffref.py OUT.h [BASE]      (run from mega65/, data files in ..)
"""
import os
import subprocess
import sys
import tempfile

out = sys.argv[1]
BASE = sys.argv[2] if len(sys.argv) > 2 else "3d41ccc"

src = subprocess.check_output(["git", "show", f"{BASE}:id_ca.cpp"]).decode("latin-1")
i = src.index("static void CAL_HuffExpand")
j = src.index("\n}\n", i) + 3
huff = src[i:j]

prog = r'''
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
typedef uint8_t byte;
typedef uint16_t word;
static void Quit(const char *s) { fprintf(stderr, "%s\n", s); exit(1); }
#include "gfxv_apo.h"
typedef struct { word bit0, bit1; } huffnode;
''' + huff + r'''
static byte *load(const char *n, long *len)
{
    FILE *f = fopen(n, "rb"); if (!f) { perror(n); exit(1); }
    fseek(f, 0, SEEK_END); *len = ftell(f); fseek(f, 0, SEEK_SET);
    byte *p = (byte *)malloc(*len + 16); fread(p, 1, *len, f); fclose(f);
    return p;
}
int main(void)
{
    long dl, hl, gl;
    huffnode *dict = (huffnode *)load("VGADICT.WL1", &dl);
    byte *head = load("VGAHEAD.WL1", &hl);
    byte *gr = load("VGAGRAPH.WL1", &gl);
    // Shareware data lacks the last chunks (numEpisodesMissing in the game),
    // so the header, not NUMCHUNKS, says how many there are.
    int nchunks = hl / 3 - 1;
    long starts[NUMCHUNKS + 1];
    for (int c = 0; c <= nchunks; c++) {
        long v = head[c*3] | head[c*3+1] << 8 | head[c*3+2] << 16;
        starts[c] = v == 0xFFFFFF ? -1 : v;
    }
    unsigned long total = 0;
    printf("// Generated by tools/gen_huffref.py -- do not edit.\n");
    printf("#define REF_NUMCHUNKS %d\n", nchunks);
    printf("static const struct { int32_t explen; uint8_t hdr; uint16_t sa, sb; } ref[] = {\n");
    for (int c = 0; c < nchunks; c++) {
        long pos = starts[c];
        if (pos < 0) { printf("  {-1, 0, 0, 0},\n"); continue; }
        long explen; int hdr = 0; byte *source = gr + pos;
        if (c >= STARTTILE8 && c < STARTEXTERNS) {
            if (c < STARTTILE8M) explen = 64 * NUMTILE8;
            else if (c < STARTTILE16) explen = 128 * NUMTILE8M;
            else if (c < STARTTILE16M) explen = 64 * 4;
            else if (c < STARTTILE32) explen = 128 * 4;
            else if (c < STARTTILE32M) explen = 64 * 16;
            else explen = 128 * 16;
        } else {
            explen = source[0] | source[1] << 8 | source[2] << 16 | (long)source[3] << 24;
            source += 4; hdr = 4;
        }
        byte *dest = (byte *)malloc(explen);
        CAL_HuffExpand(source, dest, explen, dict);
        uint16_t a = 0, b = 0;
        for (long k = 0; k < explen; k++) { a += dest[k]; b += a; }
        printf("  {%ld, %d, %u, %u},\n", explen, hdr, a, b);
        total += explen;
        free(dest);
    }
    printf("};\n#define REF_TOTAL %luUL\n", total);
    return 0;
}
'''

with tempfile.TemporaryDirectory() as tmp:
    c = os.path.join(tmp, "huffref.cpp")
    exe = os.path.join(tmp, "huffref")
    open(c, "w").write(prog)
    subprocess.check_call(["g++", "-O1", "-w", "-I..", "-DCARMACIZED", "-DUPLOAD", "-o", exe, c])
    data = subprocess.check_output([exe], cwd="..")
open(out, "wb").write(data)
