#!/usr/bin/env python3
"""Reference data for the MEGA65 cache test (see catest.cpp): checksums of
every map plane, decompressed on the host with the *original* Carmack and
RLEW expanders from git revision BASE of id_ca.cpp.

usage: gen_mapref.py OUT.h [BASE]      (run from mega65/, data files in ..)
"""
import os
import subprocess
import sys
import tempfile

out = sys.argv[1]
BASE = sys.argv[2] if len(sys.argv) > 2 else "3d41ccc"

src = subprocess.check_output(["git", "show", f"{BASE}:id_ca.cpp"]).decode("latin-1")


def func(name):
    i = src.index(name)
    return src[i:src.index("\n}\n", i) + 3]


prog = r'''
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
typedef uint8_t byte;
typedef uint16_t word;
#define NEARTAG 0xa7
#define FARTAG  0xa8
static inline word READWORD(byte *&ptr) { word v = ptr[0] | ptr[1] << 8; ptr += 2; return v; }
''' + func("void CAL_CarmackExpand") + func("void CA_RLEWexpand") + r'''
static byte *load(const char *n, long *len)
{
    FILE *f = fopen(n, "rb"); if (!f) { perror(n); exit(1); }
    fseek(f, 0, SEEK_END); *len = ftell(f); fseek(f, 0, SEEK_SET);
    byte *p = (byte *)malloc(*len + 16); fread(p, 1, *len, f); fclose(f);
    return p;
}
static long rd32(const byte *p) { return p[0] | p[1] << 8 | p[2] << 16 | (long)p[3] << 24; }
int main(void)
{
    long hl, gl;
    byte *head = load("MAPHEAD.WL1", &hl);
    byte *maps = load("GAMEMAPS.WL1", &gl);
    word tag = head[0] | head[1] << 8;
    printf("// Generated by tools/gen_mapref.py -- do not edit.\n");
    printf("static const struct { uint16_t sa, sb; } mapref[][2] = {\n");
    int n = 0;
    for (int m = 0; m < 60; m++) {
        long hdr = rd32(head + 2 + 4 * m);
        if (hdr <= 0) break;
        printf("  {");
        for (int plane = 0; plane < 2; plane++) {
            long pos = rd32(maps + hdr + 4 * plane);
            byte *source = maps + pos;
            word expanded = source[0] | source[1] << 8;
            word *buf2 = (word *)malloc(expanded);
            word dest[64 * 64];
            CAL_CarmackExpand(source + 2, buf2, expanded);
            CA_RLEWexpand(buf2 + 1, dest, 64 * 64 * 2, tag);
            free(buf2);
            uint16_t a = 0, b = 0;
            for (int k = 0; k < 64 * 64 * 2; k++) { a += ((byte *)dest)[k]; b += a; }
            printf("{%u, %u}%s", a, b, plane ? "" : ", ");
        }
        printf("},\n");
        n++;
    }
    printf("};\n#define REF_NUMMAPS %d\n", n);
    return 0;
}
'''

with tempfile.TemporaryDirectory() as tmp:
    c = os.path.join(tmp, "mapref.cpp")
    exe = os.path.join(tmp, "mapref")
    open(c, "w").write(prog)
    subprocess.check_call(["g++", "-O1", "-w", "-o", exe, c])
    data = subprocess.check_output([exe], cwd="..")
open(out, "wb").write(data)
