#!/usr/bin/env python3
"""Generate the libm test (see m65_libm.c): inputs plus the host libm's
results, as a C program for the llvm-mos simulator.

What matters is what the game sees after converting to float:
  - atan2: the game calls atan2((float) dy, (float) dx), which in C++ with
    glibc resolves to atan2f; its result is stored in a float.
  - atan:  CalcProjection does (float) atan(double).
So the test counts mismatches of the float results (and also reports how
many double results differ at all).

usage: gen_libmtest.py OUT.c
"""
import os
import random
import subprocess
import sys
import tempfile

random.seed(65)
a2 = []
# Game-like: integer-ish deltas (global coordinates in 1/65536 tiles, and
# tile deltas), all signs, including zeros and axis cases.
for _ in range(700):
    s = random.choice([1, 256, 65536, 1 << 20])
    a2.append((float(random.randint(-64, 64) * random.randint(1, s)),
               float(random.randint(-64, 64) * random.randint(1, s))))
for _ in range(250):
    a2.append((random.uniform(-1e6, 1e6), random.uniform(-1e6, 1e6)))
a2 += [(0.0, 1.0), (0.0, -1.0), (1.0, 0.0), (-1.0, 0.0), (1.0, 1.0), (-1.0, -1.0),
       (3.0, 4.0), (-3.0, 4.0), (3.0, -4.0), (-3.0, -4.0), (1e-30, 1.0), (1.0, 1e-30)]
at = []
# Projection-like: tan of angles across (0, pi/2), and general values.
for _ in range(350):
    at.append(random.uniform(0.0, 20.0))
for _ in range(150):
    at.append(random.uniform(-1e3, 1e3))
at += [0.0, 0.4375, 0.6875, 1.0, 1.1875, 1.5, 2.4375, 1e10, -1e10, 1e-12]

host = r'''
#include <math.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
static uint32_t fb(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }
static uint64_t db(double d) { uint64_t u; memcpy(&u, &d, 8); return u; }
int main(void)
{
    double y, x;
    printf("static const struct { float y, x; uint32_t want; } a2[] = {\n");
    while (scanf("A %la %la\n", &y, &x) == 2)
        printf("  {%a, %a, 0x%08lxUL},\n", (float) y, (float) x,
               (unsigned long) fb(atan2f((float) y, (float) x)));
    printf("};\nstatic const struct { double t; uint32_t wantf; uint64_t wantd; } at[] = {\n");
    while (scanf("T %la\n", &x) == 1)
        printf("  {%a, 0x%08lxUL, 0x%016llxULL},\n", x,
               (unsigned long) fb((float) atan(x)), (unsigned long long) db(atan(x)));
    printf("};\n");
    return 0;
}
'''

sim = r'''
#include <stdio.h>
#include <stdint.h>
#include <string.h>
double atan(double x);
double atan2(double y, double x);
static uint32_t fb(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }
static uint64_t db(double d) { uint64_t u; memcpy(&u, &d, 8); return u; }
int main(void)
{
    unsigned i, bad2 = 0, badf = 0, diffd = 0;
    for (i = 0; i < sizeof a2 / sizeof a2[0]; i++)
        if (fb((float) atan2((double) a2[i].y, (double) a2[i].x)) != a2[i].want) {
            if (!bad2) printf("first atan2 mismatch: %u\n", i);
            bad2++;
        }
    for (i = 0; i < sizeof at / sizeof at[0]; i++) {
        double r = atan(at[i].t);
        if (fb((float) r) != at[i].wantf) badf++;
        if (db(r) != at[i].wantd) diffd++;
    }
    printf("libm: atan2 %u/%u float mismatches, atan %u/%u float mismatches"
           " (%u double results differ in some bit)\n",
           bad2, (unsigned)(sizeof a2 / sizeof a2[0]),
           badf, (unsigned)(sizeof at / sizeof at[0]), diffd);
    return bad2 || badf;
}
'''

with tempfile.TemporaryDirectory() as tmp:
    c, exe = os.path.join(tmp, "h.c"), os.path.join(tmp, "h")
    open(c, "w").write(host)
    subprocess.check_call(["gcc", "-O0", "-o", exe, c, "-lm"])
    inp = "".join(f"A {y.hex()} {x.hex()}\n" for y, x in a2) + \
          "".join(f"T {t.hex()}\n" for t in at)
    table = subprocess.run([exe], input=inp.encode(), capture_output=True, check=True).stdout.decode()
open(sys.argv[1], "w").write("// Generated by tools/gen_libmtest.py -- do not edit.\n"
                             "#include <stdint.h>\n" + table + sim)
