#!/usr/bin/env python3
"""Generate hosttest/shifttest.cpp: the original precomputed palette shifts
(taken from git revision BASE) against the on-demand BuildShift in the working
copy of wl_play.cpp. Run from mega65/; see 'make test-host'.
"""
import subprocess
import sys

BASE = sys.argv[1] if len(sys.argv) > 1 else "3d41ccc"   # upstream, before any port changes


def between(s, a, b):
    i = s.index(a)
    return s[i:s.index(b, i)]


SEP = "/*\n=====================\n=\n= "
old = subprocess.check_output(["git", "show", f"{BASE}:wl_play.cpp"]).decode("latin-1")
new = open("../wl_play.cpp", encoding="latin-1").read()
old_init = between(old, "void InitRedShifts (void)", SEP + "ClearPaletteShifts")
new_build = between(new, "static SDL_Color *BuildShift", SEP + "InitRedShifts")
pal = between(open("../id_vl.cpp", encoding="latin-1").read(),
              "SDL_Color gamepal[]={", "};") + "};"

print(f'''// Generated by tools/make_shifttest.py -- do not edit.
#include <stdio.h>
typedef unsigned char Uint8;
typedef struct {{ Uint8 r, g, b, unused; }} SDL_Color;
#define RGB(r, g, b) {{(r)*255/63, (g)*255/63, (b)*255/63, 0}}
{pal}
#define NUMREDSHIFTS    6
#define REDSTEPS        8
#define NUMWHITESHIFTS  3
#define WHITESTEPS      20
SDL_Color redshifts[NUMREDSHIFTS][256];
SDL_Color whiteshifts[NUMWHITESHIFTS][256];
static SDL_Color shiftpal[256];
static int shiftpalkind, shiftpalstep;
{old_init}
{new_build}
static int same(const SDL_Color *a, const SDL_Color *b)
{{
    for (int j = 0; j < 256; j++)
        if (a[j].r != b[j].r || a[j].g != b[j].g || a[j].b != b[j].b) return 0;
    return 1;
}}
int main(void)
{{
    int bad = 0;
    InitRedShifts();
    for (int i = 1; i <= NUMREDSHIFTS; i++)   bad += !same(redshifts[i - 1],   BuildShift(1, i));
    for (int i = 1; i <= NUMWHITESHIFTS; i++) bad += !same(whiteshifts[i - 1], BuildShift(2, i));
    for (int i = NUMREDSHIFTS; i >= 1; i--)   bad += !same(redshifts[i - 1],   BuildShift(1, i));
    bad += !same(whiteshifts[1], BuildShift(2, 2));
    bad += !same(whiteshifts[1], BuildShift(2, 2));   // cached path
    printf("palette shifts: sizeof(int)=%d mismatches=%d\\n", (int)sizeof(int), bad);
    return bad != 0;
}}''')
